### ISSUE TITLE
add terms and conditions page

### ISSUE THREAD

**Issue by bluesomewhere** [northbaypython/website#12]

**Comment by bluesomewhere** [comment]
page added, still lacks content. will use copy from PyCon AU/LCA then refine, will also run it by Tony at Conservancy before submitting PR.

**Comment by bluesomewhere** [comment]
drafted and sent to SFC's general counsel for review before I commit and we publish

**Comment by bluesomewhere** [comment]
first round of review, advised us to add photography policy, adjustments to refund policy. waiting for second round of review.

now there concerns about the license of the copy >.< linux australia slapped a gpl license on it, though they may not have had the right to do so, it's all very confusing. waiting for a response from linux australia and tony.

**Comment by bluesomewhere** [comment]
we'll do a clean room write of our own T&C's sometime before we start selling tickets

**Comment by chrisjrn** [comment]
Happily, Linux Australia are in the process of obtaining permission to remove the GPL from their policies repo. We should have permission to use it before too long.
