### ISSUE TITLE
Add fields to the speaker profile

### ISSUE THREAD

**Issue by chrisjrn** [northbaypython/website#26]
- [x]  Twitter username
- [x]  Prior speaking experience
- [x]  Do you require travel assistance in order to present?
- [x]  Do you require accommodation assistance in order to present?
- [x]  Which city, state/province (if applicable), and country do you live in?
- [x]  Do you identify as belonging to one or more underrepresented groups in tech?
- [x]  Is this your first time speaking at a conference?
- [x]  I have read and, in the event that my proposal is accepted, agree that I will comply with the Code of Conduct

**Comment by chrisjrn** [comment]
@skimbrel Please list anything else that you think belongs here

**Comment by skimbrel** [comment]
Two things:

- Some sort of field for professional background? Drop-down with "other/fill-in-the-blank" to help us bucket between "tech industry", "education", "client services", ...?
- Phone number and/or other contact info

**Comment by chrisjrn** [comment]
We ask for phone numbers when we register. We'll have e-mail addresses for speakers.
