### ISSUE TITLE
Add fields to the proposal form

### ISSUE THREAD

**Issue by chrisjrn** [northbaypython/website#27]
Currently we have:

- Title
- 400-character description
- Abstract
- Additional notes

We should add:

- [x]  This proposal should be considered for an extended (45-minute) slot. (Please explain in your additional notes how you intend to use the extra 15 minutes).
- [x]  This proposal has not been presented at another conference.
- [x]  I authorize North Bay Python to release a copy of my slides under the Creative Commons Attribution-ShareAlike 3.0 United States licence, and certify that I have the authority to do so. (Selected by default)
- [x]  I authorize North Bay Python to release a recording of my talk under the Creative Commons Attribution-ShareAlike 3.0 United States licence.

**Comment by chrisjrn** [comment]
@skimbrel please add anything you think is important here

**Comment by skimbrel** [comment]
- [x] Do you require A/V support beyond a standard HDMI projector hookup and optional audio to most effectively present your material? 

I personally find I benefit from conferences requiring at least a rough outline in the submission — helps make sure I'm a little more prepared well in advance as a speaker, and gives more insight into the structure of the talk as a reviewer.
