### ISSUE TITLE
address accessibility concerns

### ISSUE THREAD

**Issue by bluesomewhere** [northbaypython/website#29]
add alt and title tags, make sure tab does reasonable things etc

- [x] tab works on content pages, sign up/login forms, and speaker/proposal forms
- [x] alt and title tags
- [x] check contrast when design is mostly done
- [x] make sure link focus borders are not removed by CSS
- [x] make sure hover makes it clear what link/nav item is active or selected

**Comment by joshsimmons** [comment]
added titles to all the links. images already have alt tags. tab does sensible things, provided the markdown editor is removed and replaced with a plain textarea.

need to check contrast when design is mostly done. make sure link focus borders are not removed by CSS, make sure hover makes it clear what link/nav item is active or selected.

**Comment by joshsimmons** [comment]
replaced markdown editor with general textarea, tabbing now makes sense on content pages, on sign up, login, speaker bio, and proposal forms.
