### ISSUE TITLE
address accessibility issues reported by Nic

### ISSUE THREAD

**Issue by bluesomewhere** [northbaypython/website#59]
Copying Nic's note here for us to break down and address later:

> Hello Sam and Josh,
>
> A quick look at the demo site that Sam linked me to shows that by and large, you're in good shape. But there are a couple bugs that might benefit from fixing. I don't have time to do more than that quick look at the moment, but I hope it helps.
> 
> Please note, I was going to look at the paper submission page, but couldn't get passed registration, getting 500 internal error. I assume that part of the site isn't live yet, but if it is, there may be issues.
> 
> Accessibility issues, in no particular order.
> 
> The hamburger menu in small viewports uses font awesome in a button. Basically, that means the button is empty and screen reader can't make sense of the purpose of it.
> 
> The contrast of the hamburger menu (dark grey against green) is hard to see.
> 
> Some labels (including the subscription form) use display:none to hide. This CSS declaration is respected by screen reader, so you basically just hid the labels from people who most need it. Use something like this instead:
> 
> .hidden-accessible {
>   border:0 none;
>   clip:rect(0px,0px,0px,0px);
>   height:1px;
>   margin:-1px;
>   overflow:hidden;
>   padding:0;
>   position:absolute;
>   width:1px
> }
> 
> The title attribute is used on links and other elements. This doesn't improve accessibility. Not all screen reader actually access the title attribute. For those who do, you just created repetitive announcement of what the element is about.
> 
> Increasing text size (not just zooming the page) to 200% causes some layout breakdown. Most of it is minor, except for the name of the page, which becomes a real problem.
> 
> There's a skipped h2 in the document outline on the homepage. Skipped h4 in the About the team page.
> 
> There's a "learn more" link. title attribute is used to give more info, but as already stated, this can be a problem for many. May be more appropriate to add "screen reader only text", using the CSS I gave earlier in the email.
> 
> Staff procedure under "safety" would gain from being broken down in chunks with headings to separate it. will make it easier to read.

**Comment by chrisjrn** [comment]
- [x] The hamburger menu in small viewports uses font awesome in a button. Basically, that means the button is empty and screen reader can't make sense of the purpose of it.
- [x] The contrast of the hamburger menu (dark grey against green) is hard to see.
- [x] Some labels (including the subscription form) use display:none to hide. 
- [x] Title attribute needs to go on links
- [ ] Increasing text size (not just zooming the page) to 200% causes some layout breakdown
- [x] There's a skipped h2 in the document outline on the homepage. 
- [x] Skipped h4 in the About the team page.
